= Master Boot Record (MBR) partition table
Analysis of the MBR partition table

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary
The Master Boot Record (MBR) Partition Table is a partitioning schema mainly
used on the family of Intel x86 based computers. It was first introduced on the
IBM personal computer (PC).

This document is intended as a working document for the MBR partition table
specification.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the x86 partition table.
| Classification: | Public
| Keywords: | Master Boot Record, x86 partition table, DOS partition table, Intel partition table
|===

[preface]
== License
....
Copyright (C) 2010-2018, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | July 2010 | Initial version.
| 0.0.2 | J.B. Metz | May 2012 | Applied updates.
| 0.0.3 | J.B. Metz | December 2012 | Applied updates.
| 0.0.4 | J.B. Metz | December 2012 | Additional information regarding MBR variants.
| 0.0.5 | J.B. Metz | January 2018 | Switched to asciidoc format.
|===

:numbered:
== Overview
The Master Boot Record (MBR) partition table is mainly used on the family of 
Intel x86 based computers.

The MBR partition table consists of:

* Master Boot Record (MBR)
* Extended Partition Records (EPRs)

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | 
| Character strings | 
|===

=== Terminology
Physical block:
fixed location on the storage media defined by the storage media.

Logical block:
abstract location on the storage media defined by software.

=== 512 versus 4096 bytes per sector

....
MBR sigature at offset 510 for both 512 and 4k sector size

check offset of first partition start (sector 1) which should be at 4096 instead of 512
....

== Cylinder Head Sector (CHS) address
The Cylinder Head Sector (CHS) address is 24 bits of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0.0  | 8 bits | | Head
| 1.0  | 6 bits | | Sector
| 1.5 | 10 bits | | Cylinder
|===

The logical block address (LBA) can be determined from the CHS with the 
following calculation:
....
LBA = ( ( ( cylinder x heads per cylinder ) + head ) x sectors per track )
    + sector - 1
....

== The Master Boot Record (MBR)
The Master Boot Record (MBR) is a data structure that describes the properties 
of the storage medium and its partitions.

The classical MBR can only contain 4 partition table entries. Additional 
partition entries must be stored using extended partition records (EBR). The 
classical MBR has evolved into different variants like:

* The modern MBR
* The Advanced Active Partitions (AAP) MBR
* The NEWLDR MBR
* The AST/NEC MS-DOS and SpeedStor MBR
* The Disk Manager MBR

Also see the following paragraphs for more information.

=== The classical MBR
The classical MBR is 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 446 | | The boot (loader) code
| 446 | 16 | | Partition table entry 1
| 462 | 16 | | Partition table entry 2
| 478 | 16 | | Partition table entry 3
| 494 | 16 | | Partition table entry 4
| 510 | 2 | "\x55\xaa" | The (boot) signature
|===

=== The modern MBR
The modern MBR is 512 bytes of size and consists of:

The modern MBR is 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 218 | 
4+| _The first part of the boot (loader) code_ +
Microsoft Windows 95, 98 and ME. Also see: [SEDORY04]
| *218* | *2* | *0x0000* | [yellow-background]*Unknown (Reserved)*
| *220* | *1* | | [yellow-background]*Unknown (Original physical drive)* +
*Contains a value that ranges from 0x80 to 0xff, where 0x80 is the first drive, 0x81 the second, etc.
| *221 | *1* | | *Seconds* +
*Contains a value that ranges from 0 to 59*
| *222 | *1* | | *Minutes* +
*Contains a value that ranges from 0 to 59*
| *223 | *1* | | *Hours* +
*Contains a value that ranges from 0 to 23*
4+| _Without disk identity_
| 224 | 222 | | The second part of the boot (loader) code
4+| _With disk identity - UEFI, Microsoft Windows NT or later_
| 224 | 216 | | The second part of the boot (loader) code
| *440* | *4* | | *Disk identity (signature)*
| *444* | *2* | *0x0000* | *Padding*
4+| _Common_
| 446 | 16 | | Partition table entry 1
| 462 | 16 | | Partition table entry 2
| 478 | 16 | | Partition table entry 3
| 494 | 16 | | Partition table entry 4
| 510 | 2 | "\x55\xaa" | The (boot) signature
|===

=== The Advanced Active Partitions (AAP) MBR
The Advanced Active Partitions (AAP) MBR is used by:

* PTS-DOS 6.60
* DR-DOS 7.07

The AAP MBR is 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 428 | | The boot (loader) code
| 428 | 2 | "\x78\x56" | The AAP signature
| 430 | 1 | | [yellow-background]*AAP physical drive (80h-FEh; 00h: not used; 01h-7Fh, FFh: reserved*
| 431 | 3 | | [yellow-background]*CHS (start) address of AAP partition/image file or VBR/EBR*
| 434 | 1 | | [yellow-background]*Reserved for AAP partition type (00h if not used) (optional)*
| 435 | 3 | | [yellow-background]*Reserved for CHS end address in AAP (optional; byte at offset +1B5h is also used for MBR checksum (PTS DE, BootWizard); 000000h if not used)*
| 438 | 4 | | [yellow-background]*Start LBA of AAP image file or VBR/EBR or relative sectors of AAP partition (copied to offset +01Ch in the loaded sector over the "hidden sectors" entry of a DOS 3.31 BPB (or emulation thereof) to also support EBR booting)*
| 442 | 4 | | [yellow-background]*Reserved for sectors in AAP (optional; 00000000h if not used)*
| 446 | 16 | | Partition table entry 1
| 462 | 16 | | Partition table entry 2
| 478 | 16 | | Partition table entry 3
| 494 | 16 | | Partition table entry 4
| 510 | 2 | "\x55\xaa" | The (boot) signature
|===

[yellow-background]*TODO: determine if the AAP is optional*

=== The NEWLDR MBR
The NEWLDR MBR is a variant based on the Advanced Active Partitions (AAP) MBR 
and is used by:

* DR-DOS 7.07

The NEWLDR MBR is 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | 0xeb, ...  | The initial jump instruction of the boot (loader) code
| 2 | 6 | "NEWLDR" | The NEWLDR signature
| 8 | 1 | | [yellow-background]*LOADER physical drive and boot flag (80h-FEh, 00h-7Eh, FFh, 7Fh) (if not used, this and following 3 bytes must be all 0)*
| 9 | 3 | | [yellow-background]*CHS address of LOADER boot sector or image file (f.e. IBMBIO.LDR) (000000h if not used)*
| 12 | 1 | | [yellow-background]*allowed DL minimum, else take from partition table (80h: default; 00h: always use DL; FFh: always use table entry)*
| 13 | 3 | 0x000000 | [yellow-background]*Unknown (Reserved)**
| 16 | 4 | | [yellow-background]*LBA of LOADER boot sector or image file (optional, 00000000h if not used)*
| 20 | 2 | | [yellow-background]*patch offset of VBR boot unit (default 0000h if not used, else 0024h or 01FDh)*
| 22 | 2 | | [yellow-background]*checksum (0000h if not used)*
| 24 | 6 | | [yellow-background]*OEM loader signature ("MSWIN4" for REAL/32, see also offset +0DAh, corresponds with OEM label at offset +003h in VBRs (optional)*
| 30 | 398 | | The boot (loader) code
| 428 | 2 | "\x78\x56" | The AAP signature
| 430 | 1 | | [yellow-background]*AAP physical drive (80h-FEh; 00h: not used; 01h-7Fh, FFh: reserved*
| 431 | 3 | | [yellow-background]*CHS (start) address of AAP partition/image file or VBR/EBR*
| 434 | 1 | | [yellow-background]*Reserved for AAP partition type (00h if not used) (optional)*
| 435 | 3 | | [yellow-background]*Reserved for CHS end address in AAP (optional; byte at offset +1B5h is also used for MBR checksum (PTS DE, BootWizard); 000000h if not used)*
| 438 | 4 | | [yellow-background]*Start LBA of AAP image file or VBR/EBR or relative sectors of AAP partition (copied to offset +01Ch in the loaded sector over the "hidden sectors" entry of a DOS 3.31 BPB (or emulation thereof) to also support EBR booting)*
| 442 | 4 | | [yellow-background]*Reserved for sectors in AAP (optional; 00000000h if not used)*
| 446 | 16 | | Partition table entry 1
| 462 | 16 | | Partition table entry 2
| 478 | 16 | | Partition table entry 3
| 494 | 16 | | Partition table entry 4
| 510 | 2 | "\x55\xaa" | The (boot) signature
|===

[yellow-background]*TODO: determine if the AAP is optional*

=== The AST/NEC MS-DOS and SpeedStor MBR
The AST/NEC MS-DOS and SpeedStor MBR is used by:

* AST/NEC MS-DOS
* SpeedStor

The AST/NEC MS-DOS and SpeedStor MBR is 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 380 | | The boot (loader) code
| *380* | *2* | *"\x5a\xa5"* | *The AST/NEC MS-DOS signature* +
[yellow-background]*TODO: determine if this is not used by SpeedStor?*
| *382* | *16* | | *Partition table entry 8*
| *398* | *16* | | *Partition table entry 7*
| *414* | *16* | | *Partition table entry 6*
| *430* | *16* | | *Partition table entry 5*
| 446 | 16 | | Partition table entry 1
| 462 | 16 | | Partition table entry 2
| 478 | 16 | | Partition table entry 3
| 494 | 16 | | Partition table entry 4
| 510 | 2 | "\x55\xaa" | The (boot) signature
|===

=== The Disk Manager MBR
The Disk Manager MBR is 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 252 | | The boot (loader) code
| *252* | *2* | *"\x55\xaa"* | *The Disk Manager signature*
| *254* | *16* | | *Partition table entry*
| *270* | *16* | | *Partition table entry*
| *286* | *16* | | *Partition table entry*
| *302* | *16* | | *Partition table entry*
| *318* | *16* | | *Partition table entry*
| *334* | *16* | | *Partition table entry*
| *350* | *16* | | *Partition table entry*
| *366* | *16* | | *Partition table entry*
| *382* | *16* | | *Partition table entry*
| *398* | *16* | | *Partition table entry*
| *414* | *16* | | *Partition table entry*
| *430* | *16* | | *Partition table entry*
| 446 | 16 | | Partition table entry 1
| 462 | 16 | | Partition table entry 2
| 478 | 16 | | Partition table entry 3
| 494 | 16 | | Partition table entry 4
| 510 | 2 | "\x55\xaa" | The (boot) signature
|===

== The extended partition record
The extended partition record (EBR) starts with a 64 byte (extended) partition 
record (EPR) like the MBR. This partition table contains information about the 
logical partition (volume) and additional extended partition tables.

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 446 | | [yellow-background]*Unknown (Unused)* +
Should contain zero bytes
| 446 | 16 | | Partition table entry 1
| 462 | 16 | | Partition table entry 2 +
Should contain an extended partition
| 478 | 16 | | Partition table entry 3 +
Unused and should contain zero bytes
| 494 | 16 | | Partition table entry 4 +
Unused and should contain zero bytes
| 510 | 2 | "\x55\xaa" | Signature
|===

The second partition entry contains an extended partition which points to the 
next EPR. The LBA addresses in the EPR are relative to the start of the EPR.

[NOTE]
What about CHS addresses?

== The partition table entry
The partition table entry is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Partition flags +
See section: <<partition_flags,Partition flags>>
| 1 | 3 | | The partition start address +
Value in CHS relative from the start of the harddisk
| 4 | 1 | | Partition type +
See section: <<partition_types,Partition types>>
| 5 | 3 | | The partition end address +
Value in CHS relative from the start of the harddisk
| 8 | 4 | | The partition start address +
Value in LBA (sectors) relative from the start of the harddisk
| 12 | 4 | | Size of the partition in number of sectors
|===

=== [[partition_flags]]Partition flags
The partition flags consist of the following values:

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x80 | | Partition is boot-able
|===

=== [[partition_types]]Partition types
The partition types consist of the following values:

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00 | | Empty
| 0x01 | | FAT12 (CHS)
| 0x02 | | XENIX root
| 0x02 | | XENIX user
| 0x04 | | FAT16 (16 MiB -32 MiB CHS)
| 0x05 | | Extended (CHS)
| 0x06 | | FAT16 (32 MiB - 2 GiB CHS)
| 0x07 | | HPFS/NTFS
| 0x08 | | AIX
| 0x09 | | AIX bootable
| 0x0a | | OS/2 Boot Manager
| 0x0b | | FAT32 (CHS)
| 0x0c | | FAT32 (LBA)
| | |
| 0x0e | | FAT16 (32 MiB - 2 GiB LBA)
| 0x0f | | Extended (LBA)
| 0x10 | | OPUS
| 0x11 | | Hidden FAT12 (CHS)
| 0x12 | | Compaq diagnostics
| | |
| 0x14 | | Hidden FAT16 (16 MiB - 32 MiB CHS)
| | |
| 0x16 | | Hidden FAT16 (32 MiB - 2 GiB CHS)
| 0x17 | | Hidden HPFS/NTFS
| 0x18 | | AST SmartSleep
| | | 
| 0x1b | | Hidden FAT32 (CHS)
| 0x1c | | Hidden FAT32 (LBA)
| | | 
| 0x1e | | Hidden FAT16 (32 MiB - 2 GiB LBA)
| | | 
| 0x24 | | NEC DOS
| | | 
| 0x27 | | [yellow-background]*Unknown (PackardBell recovery/installation partition)*
| | | 
| 0x39 | | Plan 9
| | | 
| 0x3c | | PartitionMagic recovery
| | | 
| 0x40 | | Venix 80286
| 0x41 | | PPC PReP Boot
| 0x42 | | SFS +
LDM: Microsoft MBR (Dynamic Disk)
| | | 
| 0x4d | | QNX4.x
| 0x4e | | QNX4.x 2nd part
| 0x4f | | QNX4.x 3rd part
| 0x50 | | OnTrack DM
| 0x51 | | OnTrack DM6 Aux1
| 0x52 | | CP/M
| 0x53 | | OnTrack DM6 Aux3
| 0x54 | | OnTrackDM6
| 0x55 | | EZ-Drive
| 0x56 | | Golden Bow
| | | 
| 0x5c | | Priam Edisk
| | | 
| 0x61 | | SpeedStor
| | | 
| 0x63 | | GNU HURD or SysV
| 0x64 | | Novell Netware 286
| 0x65 | | Novell Netware 386
| | | 
| 0x70 | | DiskSecure Multi-Boot
| | | 
| 0x75 | | PC/IX
| | | 
| 0x78 | | XOSL
| | | 
| 0x80 | | Old Minix
| 0x81 | | Minix / old Linux
| 0x82 | | Solaris x86 +
Linux swap
| 0x83 | | Linux
| 0x84 | | Hibernation +
OS/2 hidden C: drive
| 0x85 | | Linux extended
| 0x86 | | NTFS volume set
| 0x87 | | NTFS volume set
| | | 
| 0x8e | | Linux LVM
| | | 
| 0x93 | | Amoeba
| 0x94 | | Amoeba BBT
| | | 
| 0x9f | | BSD/OS
| 0xa0 | | IBM Thinkpad hibernation
| 0xa1 | | Hibernation
| | | 
| 0xa5 | | FreeBSD
| 0xa6 | | OpenBSD
| 0xa7 | | NeXTSTEP
| 0xa8 | | Mac OS X
| 0xa9 | | NetBSD
| | | 
| 0xab | | Mac OS X Boot
| | | 
| 0xaf | | Mac OS X
| | | 
| 0xb7 | | BSDI
| 0xb8 | | BSDI swap
| | | 
| 0xbb | | Boot Wizard hidden
| | | 
| 0xc1 | | DRDOS/sec (FAT-12)
| | | 
| 0xc4 | | DRDOS/sec (FAT-16 < 32M)
| | | 
| 0xc6 | | DRDOS/sec (FAT-16)
| 0xc7 | | Syrinx
| | | 
| 0xda | | Non-FS data
| 0xdb | | CP/M / CTOS / ...
| | | 
| 0xde | | Dell Utility
| 0xdf | | BootIt
| | | 
| 0xe1 | | DOS access
| | | 
| 0xe3 | | DOS R/O
| 0xe4 | | SpeedStor
| | | 
| 0xeb | | BeOS
| | | 
| 0xee | | EFI GPT protective partition
| 0xef | | EFI system partition (FAT)
| 0xf0 | | Linux/PA-RISC boot
| 0xf1 | | SpeedStor
| 0xf2 | | DOS secondary
| | | 
| 0xf4 | | SpeedStor
| | | 
| 0xfb | | VMWare file system
| 0xfc | | VMWare swap
| 0xfd | | Linux RAID auto-detect
| 0xfe | | LANstep
| 0xff | | BBT
|===

:numbered!:
[appendix]
== References

`[PFISTERER03]`

[cols="1,5",options="header"]
|===
| Title: | disktype
| Author(s): | Christoph Pfisterer
| Date: | 2003
| URL: | http://disktype.sourceforge.net/
|===

`[SEDORY04]`

[cols="1,5",options="header"]
|===
| Title: | The Mystery Bytes (or the Drive/Timestamp Bytes) of the MS-Windows™ 95B, 98, 98SE and Me Master Boot Record (MBR)
| Author(s): | Daniel B. Sedory
| Date: | 2004
| URL: | http://thestarman.pcministry.com/asm/mbr/mystery.htm
|===

`[SLEUTHKIT]`

[cols="1,5",options="header"]
|===
| Title: | sleuthkit
| Author(s): | Brian Carrier
| URL: | http://www.sleuthkit.org/
|===

[cols="1,5",options="header"]
|===
| Title: | Extended Boot Record
| URL: | http://en.wikipedia.org/wiki/Extended_Boot_Record
|===

[cols="1,5",options="header"]
|===
| Title: | Master Boot Record
| URL: | http://en.wikipedia.org/wiki/Master_boot_record
|===

[cols="1,5",options="header"]
|===
| Title: | Unified Extensible Firmware Interface
| URL: | http://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

